name=input("Enter your name:")
mark=int(input("Enter your mark:"))
percentage=float(input("Enter your percentage:"))
print("Name:",name)
print("Mark:",mark)
print("Percentage:",percentage)
print(type(name))
print(type(mark))
print(type(percentage))
